"""initial

Revision ID: 2f32c3ee42e7
Revises: 
Create Date: 2023-10-27 15:39:00.219683

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2f32c3ee42e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('UUID', postgresql.UUID(), nullable=False),
    sa.Column('Login', sa.String(), nullable=False),
    sa.Column('DisplayName', sa.String(), nullable=False),
    sa.Column('added_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('Phone', sa.String(), nullable=True),
    sa.Column('Telegram', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('UUID')
    )
    op.create_table('user_groups',
    sa.Column('UID', postgresql.UUID(), nullable=True),
    sa.Column('G_UID', postgresql.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['UID'], ['user.UUID'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_groups')
    op.drop_table('user')
    # ### end Alembic commands ###
